//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.10 at 11:39:38 AM ICT 
//


package org.mobilink.activity.model;

import java.util.ArrayList;
import java.util.List;

import javax.ws.rs.FormParam;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="doItem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="seqNum" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="participantId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="activityTemplateId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="activityStateId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="days" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="docFileTemplateId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="docArchiveTemplateId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element ref="{}AtvPreChecklistModel" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "doItem",
    "seqNum",
    "participantId",
    "activityTemplateId",
    "activityStateId",
    "days",
    "docFileTemplateId",
    "docArchiveTemplateId",
    "atvPreChecklistModel"
})
@XmlRootElement(name = "AtvChecklistInputModel")
public class AtvChecklistInputModel {

    @FormParam("type")
    protected Integer type;
    @FormParam("doItem")
    protected String doItem;
    @FormParam("seqNum")
    protected Integer seqNum;
    @FormParam("participantId")
    protected Long participantId;
    @FormParam("activityTemplateId")
    protected Long activityTemplateId;
    @FormParam("activityStateId")
    protected Long activityStateId;
    @FormParam("days")
    protected Integer days;
    @FormParam("docFileTemplateId")
    protected Long docFileTemplateId;
    @FormParam("docArchiveTemplateId")
    protected Long docArchiveTemplateId;
    @FormParam("preChecklists")
    @XmlElement(name = "preChecklists")
    protected List<AtvPreChecklistModel> atvPreChecklistModel;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setType(Integer value) {
        this.type = value;
    }

    /**
     * Gets the value of the doItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoItem() {
        return doItem;
    }

    /**
     * Sets the value of the doItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoItem(String value) {
        this.doItem = value;
    }

    /**
     * Gets the value of the seqNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeqNum(Integer value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the participantId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getParticipantId() {
        return participantId;
    }

    /**
     * Sets the value of the participantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setParticipantId(Long value) {
        this.participantId = value;
    }

    /**
     * Gets the value of the activityTemplateId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getActivityTemplateId() {
        return activityTemplateId;
    }

    /**
     * Sets the value of the activityTemplateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setActivityTemplateId(Long value) {
        this.activityTemplateId = value;
    }

    /**
     * Gets the value of the activityStateId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getActivityStateId() {
        return activityStateId;
    }

    /**
     * Sets the value of the activityStateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setActivityStateId(Long value) {
        this.activityStateId = value;
    }

    /**
     * Gets the value of the days property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDays() {
        return days;
    }

    /**
     * Sets the value of the days property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDays(Integer value) {
        this.days = value;
    }

    /**
     * Gets the value of the docFileTemplateId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDocFileTemplateId() {
        return docFileTemplateId;
    }

    /**
     * Sets the value of the docFileTemplateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDocFileTemplateId(Long value) {
        this.docFileTemplateId = value;
    }

    /**
     * Gets the value of the docArchiveTemplateId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDocArchiveTemplateId() {
        return docArchiveTemplateId;
    }

    /**
     * Sets the value of the docArchiveTemplateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDocArchiveTemplateId(Long value) {
        this.docArchiveTemplateId = value;
    }

    /**
     * Gets the value of the atvPreChecklistModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the atvPreChecklistModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAtvPreChecklistModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AtvPreChecklistModel }
     * 
     * 
     */
    public List<AtvPreChecklistModel> getAtvPreChecklistModel() {
        if (atvPreChecklistModel == null) {
            atvPreChecklistModel = new ArrayList<AtvPreChecklistModel>();
        }
        return this.atvPreChecklistModel;
    }

}
