//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 09:04:35 AM ICT 
//


package org.mobilink.activity.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mobilink.api.activity.model.tmp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mobilink.api.activity.model.tmp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AtvChecklistModel }
     * 
     */
    public AtvChecklistModel createAtvChecklistModel() {
        return new AtvChecklistModel();
    }

    /**
     * Create an instance of {@link AtvPreChecklistModel }
     * 
     */
    public AtvPreChecklistModel createAtvPreChecklistModel() {
        return new AtvPreChecklistModel();
    }

    /**
     * Create an instance of {@link AtvWorkspaceResultsModel }
     * 
     */
    public AtvWorkspaceResultsModel createAtvWorkspaceResultsModel() {
        return new AtvWorkspaceResultsModel();
    }

    /**
     * Create an instance of {@link AtvWorkspacceModel }
     * 
     */
    public AtvWorkspacceModel createAtvWorkspacceModel() {
        return new AtvWorkspacceModel();
    }

    /**
     * Create an instance of {@link AtvArchiveResultsModel }
     * 
     */
    public AtvArchiveResultsModel createAtvArchiveResultsModel() {
        return new AtvArchiveResultsModel();
    }

    /**
     * Create an instance of {@link AtvArchiveModel }
     * 
     */
    public AtvArchiveModel createAtvArchiveModel() {
        return new AtvArchiveModel();
    }

    /**
     * Create an instance of {@link AtvRatingInputModel }
     * 
     */
    public AtvRatingInputModel createAtvRatingInputModel() {
        return new AtvRatingInputModel();
    }

    /**
     * Create an instance of {@link AtvChecklistResultsModel }
     * 
     */
    public AtvChecklistResultsModel createAtvChecklistResultsModel() {
        return new AtvChecklistResultsModel();
    }

    /**
     * Create an instance of {@link AtvLabelResultsModel }
     * 
     */
    public AtvLabelResultsModel createAtvLabelResultsModel() {
        return new AtvLabelResultsModel();
    }

    /**
     * Create an instance of {@link AtvLabelModel }
     * 
     */
    public AtvLabelModel createAtvLabelModel() {
        return new AtvLabelModel();
    }

    /**
     * Create an instance of {@link AtvDocFileModel }
     * 
     */
    public AtvDocFileModel createAtvDocFileModel() {
        return new AtvDocFileModel();
    }

    /**
     * Create an instance of {@link AtvLabelInputModel }
     * 
     */
    public AtvLabelInputModel createAtvLabelInputModel() {
        return new AtvLabelInputModel();
    }

    /**
     * Create an instance of {@link AtvWorkspaceSearchModel }
     * 
     */
    public AtvWorkspaceSearchModel createAtvWorkspaceSearchModel() {
        return new AtvWorkspaceSearchModel();
    }

    /**
     * Create an instance of {@link AtvChecklistInputModel }
     * 
     */
    public AtvChecklistInputModel createAtvChecklistInputModel() {
        return new AtvChecklistInputModel();
    }

    /**
     * Create an instance of {@link AtvWorkspaceInputModel }
     * 
     */
    public AtvWorkspaceInputModel createAtvWorkspaceInputModel() {
        return new AtvWorkspaceInputModel();
    }

    /**
     * Create an instance of {@link AtvLabelSearchModel }
     * 
     */
    public AtvLabelSearchModel createAtvLabelSearchModel() {
        return new AtvLabelSearchModel();
    }

    /**
     * Create an instance of {@link AtvDocFileInputModel }
     * 
     */
    public AtvDocFileInputModel createAtvDocFileInputModel() {
        return new AtvDocFileInputModel();
    }

    /**
     * Create an instance of {@link AtvDocArchiveInputModel }
     * 
     */
    public AtvDocArchiveInputModel createAtvDocArchiveInputModel() {
        return new AtvDocArchiveInputModel();
    }

    /**
     * Create an instance of {@link AtvChecklistDoingInputModel }
     * 
     */
    public AtvChecklistDoingInputModel createAtvChecklistDoingInputModel() {
        return new AtvChecklistDoingInputModel();
    }

    /**
     * Create an instance of {@link AtvDocFileResultsModel }
     * 
     */
    public AtvDocFileResultsModel createAtvDocFileResultsModel() {
        return new AtvDocFileResultsModel();
    }

}
