//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 10:29:28 AM ICT 
//


package org.mobilink.api.statistic.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mobilink.api.statistic.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mobilink.api.statistic.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CheckListOverallRatingModel }
     * 
     */
    public CheckListOverallRatingModel createCheckListOverallRatingModel() {
        return new CheckListOverallRatingModel();
    }

    /**
     * Create an instance of {@link CklActivityMonthSearchModel }
     * 
     */
    public CklActivityMonthSearchModel createCklActivityMonthSearchModel() {
        return new CklActivityMonthSearchModel();
    }

    /**
     * Create an instance of {@link ToDoListResultsModel }
     * 
     */
    public ToDoListResultsModel createToDoListResultsModel() {
        return new ToDoListResultsModel();
    }

    /**
     * Create an instance of {@link ToDoListModel }
     * 
     */
    public ToDoListModel createToDoListModel() {
        return new ToDoListModel();
    }

    /**
     * Create an instance of {@link CheckListResultsModel }
     * 
     */
    public CheckListResultsModel createCheckListResultsModel() {
        return new CheckListResultsModel();
    }

    /**
     * Create an instance of {@link CheckListModel }
     * 
     */
    public CheckListModel createCheckListModel() {
        return new CheckListModel();
    }

    /**
     * Create an instance of {@link CheckListMonthsModel }
     * 
     */
    public CheckListMonthsModel createCheckListMonthsModel() {
        return new CheckListMonthsModel();
    }

    /**
     * Create an instance of {@link CheckListOverallModel }
     * 
     */
    public CheckListOverallModel createCheckListOverallModel() {
        return new CheckListOverallModel();
    }

    /**
     * Create an instance of {@link CklActivityUserResultsModel }
     * 
     */
    public CklActivityUserResultsModel createCklActivityUserResultsModel() {
        return new CklActivityUserResultsModel();
    }

    /**
     * Create an instance of {@link CklActivityUserModel }
     * 
     */
    public CklActivityUserModel createCklActivityUserModel() {
        return new CklActivityUserModel();
    }

    /**
     * Create an instance of {@link CklActivityMonthModel }
     * 
     */
    public CklActivityMonthModel createCklActivityMonthModel() {
        return new CklActivityMonthModel();
    }

    /**
     * Create an instance of {@link CklActivityUserSearchModel }
     * 
     */
    public CklActivityUserSearchModel createCklActivityUserSearchModel() {
        return new CklActivityUserSearchModel();
    }

    /**
     * Create an instance of {@link CheckListSearchModel }
     * 
     */
    public CheckListSearchModel createCheckListSearchModel() {
        return new CheckListSearchModel();
    }

    /**
     * Create an instance of {@link ToDoListSearchModel }
     * 
     */
    public ToDoListSearchModel createToDoListSearchModel() {
        return new ToDoListSearchModel();
    }

    /**
     * Create an instance of {@link CklActivityMonthResultsModel }
     * 
     */
    public CklActivityMonthResultsModel createCklActivityMonthResultsModel() {
        return new CklActivityMonthResultsModel();
    }

}
