//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.02 at 02:30:27 PM ICT 
//


package org.mobilink.docfile.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="docFileId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="modifiedDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="issuerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issuerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codeNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codeNotation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="promulgationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="signerInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="typeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="templateNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="register" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="registerDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="seqNum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="isNew" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="overdue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="permission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://benchresources.in/cdm/Player}LabelModel" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "docFileId",
    "userId",
    "userName",
    "createDate",
    "modifiedDate",
    "issuerCode",
    "issuerName",
    "codeNo",
    "codeNotation",
    "promulgationDate",
    "signerInfo",
    "documentType",
    "typeName",
    "subject",
    "templateNo",
    "register",
    "registerDate",
    "seqNum",
    "dueDate",
    "status",
    "isTemplate",
    "isNew",
    "overdue",
    "permission",
    "labelModel"
})
@XmlRootElement(name = "DocFileModel")
public class DocFileModel {

    protected long docFileId;
    protected long userId;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date createDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date modifiedDate;
    @XmlElement(required = true)
    protected String issuerCode;
    @XmlElement(required = true)
    protected String issuerName;
    @XmlElement(required = true)
    protected String codeNo;
    @XmlElement(required = true)
    protected String codeNotation;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date promulgationDate;
    @XmlElement(required = true)
    protected String signerInfo;
    protected int documentType;
    @XmlElement(required = true)
    protected String typeName;
    @XmlElement(required = true)
    protected String subject;
    @XmlElement(required = true)
    protected String templateNo;
    protected long register;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date registerDate;
    protected int seqNum;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date dueDate;
    @XmlElement(required = true)
    protected String status;
    protected boolean isTemplate;
    protected boolean isNew;
    protected int overdue;
    @XmlElement(required = true)
    protected String permission;
    @XmlElement(name = "labels")
    protected List<LabelModel> labelModel;

    /**
     * Gets the value of the docFileId property.
     * 
     */
    public long getDocFileId() {
        return docFileId;
    }

    /**
     * Sets the value of the docFileId property.
     * 
     */
    public void setDocFileId(long value) {
        this.docFileId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     */
    public long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(long value) {
        this.userId = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDate(Date value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifiedDate(Date value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the issuerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerCode() {
        return issuerCode;
    }

    /**
     * Sets the value of the issuerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerCode(String value) {
        this.issuerCode = value;
    }

    /**
     * Gets the value of the issuerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerName() {
        return issuerName;
    }

    /**
     * Sets the value of the issuerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerName(String value) {
        this.issuerName = value;
    }

    /**
     * Gets the value of the codeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeNo() {
        return codeNo;
    }

    /**
     * Sets the value of the codeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeNo(String value) {
        this.codeNo = value;
    }

    /**
     * Gets the value of the codeNotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeNotation() {
        return codeNotation;
    }

    /**
     * Sets the value of the codeNotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeNotation(String value) {
        this.codeNotation = value;
    }

    /**
     * Gets the value of the promulgationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getPromulgationDate() {
        return promulgationDate;
    }

    /**
     * Sets the value of the promulgationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPromulgationDate(Date value) {
        this.promulgationDate = value;
    }

    /**
     * Gets the value of the signerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignerInfo() {
        return signerInfo;
    }

    /**
     * Sets the value of the signerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignerInfo(String value) {
        this.signerInfo = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     */
    public int getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     */
    public void setDocumentType(int value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeName(String value) {
        this.typeName = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the templateNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * Sets the value of the templateNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateNo(String value) {
        this.templateNo = value;
    }

    /**
     * Gets the value of the register property.
     * 
     */
    public long getRegister() {
        return register;
    }

    /**
     * Sets the value of the register property.
     * 
     */
    public void setRegister(long value) {
        this.register = value;
    }

    /**
     * Gets the value of the registerDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * Sets the value of the registerDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegisterDate(Date value) {
        this.registerDate = value;
    }

    /**
     * Gets the value of the seqNum property.
     * 
     */
    public int getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     */
    public void setSeqNum(int value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(Date value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the isTemplate property.
     * 
     */
    public boolean isIsTemplate() {
        return isTemplate;
    }

    /**
     * Sets the value of the isTemplate property.
     * 
     */
    public void setIsTemplate(boolean value) {
        this.isTemplate = value;
    }

    /**
     * Gets the value of the isNew property.
     * 
     */
    public boolean isIsNew() {
        return isNew;
    }

    /**
     * Sets the value of the isNew property.
     * 
     */
    public void setIsNew(boolean value) {
        this.isNew = value;
    }

    /**
     * Gets the value of the overdue property.
     * 
     */
    public int getOverdue() {
        return overdue;
    }

    /**
     * Sets the value of the overdue property.
     * 
     */
    public void setOverdue(int value) {
        this.overdue = value;
    }

    /**
     * Gets the value of the permission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermission() {
        return permission;
    }

    /**
     * Sets the value of the permission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermission(String value) {
        this.permission = value;
    }

    /**
     * Gets the value of the labelModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelModel }
     * 
     * 
     */
    public List<LabelModel> getLabelModel() {
        if (labelModel == null) {
            labelModel = new ArrayList<LabelModel>();
        }
        return this.labelModel;
    }

}
