//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.02 at 02:30:27 PM ICT 
//


package org.mobilink.docfile.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="docFileId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="modifiedDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="templateNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issuerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issuerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codeNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codeNotation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="promulgationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="promulgationPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="signerInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="typeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="security" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pageAmount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="promulgationAmount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="visibility" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="archiveCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="archiveState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="register" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="registerDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="seqNum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dueDate " type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="permission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approvalDate " type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="signerUserId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="verified" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{http://benchresources.in/cdm/Player}LabelModel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://benchresources.in/cdm/Player}LinkModel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://benchresources.in/cdm/Player}ActivityModel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://benchresources.in/cdm/Player}AttachModel" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "docFileId",
    "userId",
    "userName",
    "createDate",
    "modifiedDate",
    "templateNo",
    "issuerCode",
    "issuerName",
    "codeNo",
    "codeNotation",
    "promulgationDate",
    "promulgationPlace",
    "signerInfo",
    "documentType",
    "typeName",
    "subject",
    "content",
    "security",
    "priority",
    "pageAmount",
    "promulgationAmount",
    "language",
    "visibility",
    "archiveCode",
    "archiveState",
    "register",
    "registerDate",
    "seqNum",
    "dueDate0020",
    "status",
    "isTemplate",
    "permission",
    "approvalDate0020",
    "signerUserId",
    "verified",
    "labelModel",
    "linkModel",
    "activityModel",
    "attachModel"
})
@XmlRootElement(name = "DocFileDetailModel")
public class DocFileDetailModel {

    protected long docFileId;
    protected long userId;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date createDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date modifiedDate;
    @XmlElement(required = true)
    protected String templateNo;
    @XmlElement(required = true)
    protected String issuerCode;
    @XmlElement(required = true)
    protected String issuerName;
    @XmlElement(required = true)
    protected String codeNo;
    @XmlElement(required = true)
    protected String codeNotation;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date promulgationDate;
    @XmlElement(required = true)
    protected String promulgationPlace;
    @XmlElement(required = true)
    protected String signerInfo;
    protected int documentType;
    @XmlElement(required = true)
    protected String typeName;
    @XmlElement(required = true)
    protected String subject;
    @XmlElement(required = true)
    protected String content;
    protected int security;
    protected int priority;
    protected int pageAmount;
    protected int promulgationAmount;
    @XmlElement(required = true)
    protected String language;
    protected int visibility;
    @XmlElement(required = true)
    protected String archiveCode;
    @XmlElement(required = true)
    protected String archiveState;
    protected long register;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date registerDate;
    protected int seqNum;
    @XmlElement(name = "dueDate ", required = true)
    @XmlSchemaType(name = "date")
    protected Date dueDate0020;
    @XmlElement(required = true)
    protected String status;
    protected boolean isTemplate;
    @XmlElement(required = true)
    protected String permission;
    @XmlElement(name = "approvalDate ", required = true)
    @XmlSchemaType(name = "date")
    protected Date approvalDate0020;
    protected long signerUserId;
    protected boolean verified;
    @XmlElement(name = "labels")
    protected List<LabelModel> labelModel;
    @XmlElement(name = "links")
    protected List<LinkModel> linkModel;
    @XmlElement(name = "activities")
    protected List<ActivityModel> activityModel;
    @XmlElement(name = "attachs")
    protected List<AttachModel> attachModel;

    /**
     * Gets the value of the docFileId property.
     * 
     */
    public long getDocFileId() {
        return docFileId;
    }

    /**
     * Sets the value of the docFileId property.
     * 
     */
    public void setDocFileId(long value) {
        this.docFileId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     */
    public long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(long value) {
        this.userId = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDate(Date value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifiedDate(Date value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the templateNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * Sets the value of the templateNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateNo(String value) {
        this.templateNo = value;
    }

    /**
     * Gets the value of the issuerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerCode() {
        return issuerCode;
    }

    /**
     * Sets the value of the issuerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerCode(String value) {
        this.issuerCode = value;
    }

    /**
     * Gets the value of the issuerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerName() {
        return issuerName;
    }

    /**
     * Sets the value of the issuerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerName(String value) {
        this.issuerName = value;
    }

    /**
     * Gets the value of the codeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeNo() {
        return codeNo;
    }

    /**
     * Sets the value of the codeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeNo(String value) {
        this.codeNo = value;
    }

    /**
     * Gets the value of the codeNotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeNotation() {
        return codeNotation;
    }

    /**
     * Sets the value of the codeNotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeNotation(String value) {
        this.codeNotation = value;
    }

    /**
     * Gets the value of the promulgationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getPromulgationDate() {
        return promulgationDate;
    }

    /**
     * Sets the value of the promulgationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPromulgationDate(Date value) {
        this.promulgationDate = value;
    }

    /**
     * Gets the value of the promulgationPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromulgationPlace() {
        return promulgationPlace;
    }

    /**
     * Sets the value of the promulgationPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromulgationPlace(String value) {
        this.promulgationPlace = value;
    }

    /**
     * Gets the value of the signerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignerInfo() {
        return signerInfo;
    }

    /**
     * Sets the value of the signerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignerInfo(String value) {
        this.signerInfo = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     */
    public int getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     */
    public void setDocumentType(int value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeName(String value) {
        this.typeName = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the security property.
     * 
     */
    public int getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     */
    public void setSecurity(int value) {
        this.security = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

    /**
     * Gets the value of the pageAmount property.
     * 
     */
    public int getPageAmount() {
        return pageAmount;
    }

    /**
     * Sets the value of the pageAmount property.
     * 
     */
    public void setPageAmount(int value) {
        this.pageAmount = value;
    }

    /**
     * Gets the value of the promulgationAmount property.
     * 
     */
    public int getPromulgationAmount() {
        return promulgationAmount;
    }

    /**
     * Sets the value of the promulgationAmount property.
     * 
     */
    public void setPromulgationAmount(int value) {
        this.promulgationAmount = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     */
    public int getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     */
    public void setVisibility(int value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the archiveCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiveCode() {
        return archiveCode;
    }

    /**
     * Sets the value of the archiveCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiveCode(String value) {
        this.archiveCode = value;
    }

    /**
     * Gets the value of the archiveState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiveState() {
        return archiveState;
    }

    /**
     * Sets the value of the archiveState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiveState(String value) {
        this.archiveState = value;
    }

    /**
     * Gets the value of the register property.
     * 
     */
    public long getRegister() {
        return register;
    }

    /**
     * Sets the value of the register property.
     * 
     */
    public void setRegister(long value) {
        this.register = value;
    }

    /**
     * Gets the value of the registerDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * Sets the value of the registerDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegisterDate(Date value) {
        this.registerDate = value;
    }

    /**
     * Gets the value of the seqNum property.
     * 
     */
    public int getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     */
    public void setSeqNum(int value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the dueDate0020 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getDueDate_0020() {
        return dueDate0020;
    }

    /**
     * Sets the value of the dueDate0020 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate_0020(Date value) {
        this.dueDate0020 = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the isTemplate property.
     * 
     */
    public boolean isIsTemplate() {
        return isTemplate;
    }

    /**
     * Sets the value of the isTemplate property.
     * 
     */
    public void setIsTemplate(boolean value) {
        this.isTemplate = value;
    }

    /**
     * Gets the value of the permission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermission() {
        return permission;
    }

    /**
     * Sets the value of the permission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermission(String value) {
        this.permission = value;
    }

    /**
     * Gets the value of the approvalDate0020 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getApprovalDate_0020() {
        return approvalDate0020;
    }

    /**
     * Sets the value of the approvalDate0020 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApprovalDate_0020(Date value) {
        this.approvalDate0020 = value;
    }

    /**
     * Gets the value of the signerUserId property.
     * 
     */
    public long getSignerUserId() {
        return signerUserId;
    }

    /**
     * Sets the value of the signerUserId property.
     * 
     */
    public void setSignerUserId(long value) {
        this.signerUserId = value;
    }

    /**
     * Gets the value of the verified property.
     * 
     */
    public boolean isVerified() {
        return verified;
    }

    /**
     * Sets the value of the verified property.
     * 
     */
    public void setVerified(boolean value) {
        this.verified = value;
    }

    /**
     * Gets the value of the labelModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelModel }
     * 
     * 
     */
    public List<LabelModel> getLabelModel() {
        if (labelModel == null) {
            labelModel = new ArrayList<LabelModel>();
        }
        return this.labelModel;
    }

    /**
     * Gets the value of the linkModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkModel }
     * 
     * 
     */
    public List<LinkModel> getLinkModel() {
        if (linkModel == null) {
            linkModel = new ArrayList<LinkModel>();
        }
        return this.linkModel;
    }

    /**
     * Gets the value of the activityModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activityModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivityModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActivityModel }
     * 
     * 
     */
    public List<ActivityModel> getActivityModel() {
        if (activityModel == null) {
            activityModel = new ArrayList<ActivityModel>();
        }
        return this.activityModel;
    }

    /**
     * Gets the value of the attachModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachModel }
     * 
     * 
     */
    public List<AttachModel> getAttachModel() {
        if (attachModel == null) {
            attachModel = new ArrayList<AttachModel>();
        }
        return this.attachModel;
    }

}
