//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.02 at 02:30:27 PM ICT 
//


package org.mobilink.docfile.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="docFileId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="codeNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codeNotation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="typeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "docFileId",
    "codeNo",
    "codeNotation",
    "subject",
    "typeName"
})
@XmlRootElement(name = "LinkModel")
public class LinkModel {

    protected long docFileId;
    @XmlElement(required = true)
    protected String codeNo;
    @XmlElement(required = true)
    protected String codeNotation;
    @XmlElement(required = true)
    protected String subject;
    @XmlElement(required = true)
    protected String typeName;

    /**
     * Gets the value of the docFileId property.
     * 
     */
    public long getDocFileId() {
        return docFileId;
    }

    /**
     * Sets the value of the docFileId property.
     * 
     */
    public void setDocFileId(long value) {
        this.docFileId = value;
    }

    /**
     * Gets the value of the codeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeNo() {
        return codeNo;
    }

    /**
     * Sets the value of the codeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeNo(String value) {
        this.codeNo = value;
    }

    /**
     * Gets the value of the codeNotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeNotation() {
        return codeNotation;
    }

    /**
     * Sets the value of the codeNotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeNotation(String value) {
        this.codeNotation = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeName(String value) {
        this.typeName = value;
    }

}
