//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.02 at 02:30:27 PM ICT 
//


package org.mobilink.docfile.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mobilink.docfile.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mobilink.docfile.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RolesModel }
     * 
     */
    public RolesModel createRoleModel() {
        return new RolesModel();
    }

    /**
     * Create an instance of {@link RolesInputModel }
     * 
     */
    public RolesInputModel createRoleInputModel() {
        return new RolesInputModel();
    }

    /**
     * Create an instance of {@link UserDocFileShortModel }
     * 
     */
    public UserDocFileShortModel createUserDocFileShortModel() {
        return new UserDocFileShortModel();
    }

    /**
     * Create an instance of {@link LabelShortModel }
     * 
     */
    public LabelShortModel createLabelShortModel() {
        return new LabelShortModel();
    }

    /**
     * Create an instance of {@link LinkModel }
     * 
     */
    public LinkModel createLinkModel() {
        return new LinkModel();
    }

    /**
     * Create an instance of {@link DocFileResults }
     * 
     */
    public DocFileResults createDocFileResults() {
        return new DocFileResults();
    }

    /**
     * Create an instance of {@link DocFileModel }
     * 
     */
    public DocFileModel createDocFileModel() {
        return new DocFileModel();
    }

    /**
     * Create an instance of {@link LabelModel }
     * 
     */
    public LabelModel createLabelModel() {
        return new LabelModel();
    }

   
    /**
     * Create an instance of {@link LinkResults }
     * 
     */
    public LinkResults createLinkResults() {
        return new LinkResults();
    }

    /**
     * Create an instance of {@link DocFileInputModel }
     * 
     */
    public DocFileInputModel createDocFileInputModel() {
        return new DocFileInputModel();
    }

    /**
     * Create an instance of {@link ChangeLogResults }
     * 
     */
    public ChangeLogResults createChangeLogResults() {
        return new ChangeLogResults();
    }

    /**
     * Create an instance of {@link ChangeLogModel }
     * 
     */
    public ChangeLogModel createChangeLogModel() {
        return new ChangeLogModel();
    }

    /**
     * Create an instance of {@link UserDocFileModel }
     * 
     */
    public UserDocFileModel createUserDocFileModel() {
        return new UserDocFileModel();
    }

    /**
     * Create an instance of {@link DocFileDetailModel }
     * 
     */
    public DocFileDetailModel createDocFileDetailModel() {
        return new DocFileDetailModel();
    }

    /**
     * Create an instance of {@link ActivityModel }
     * 
     */
    public ActivityModel createActivityModel() {
        return new ActivityModel();
    }

    /**
     * Create an instance of {@link AttachModel }
     * 
     */
    public AttachModel createAttachModel() {
        return new AttachModel();
    }

    /**
     * Create an instance of {@link UserDocFileResults }
     * 
     */
    public UserDocFileResults createUserDocFileResults() {
        return new UserDocFileResults();
    }

    /**
     * Create an instance of {@link UserDocFileInputModel }
     * 
     */
    public UserDocFileInputModel createUserDocFileInputModel() {
        return new UserDocFileInputModel();
    }

    /**
     * Create an instance of {@link LabelResults }
     * 
     */
    public LabelResults createLabelResults() {
        return new LabelResults();
    }

    /**
     * Create an instance of {@link ApprovalModel }
     * 
     */
    public ApprovalModel createApprovalModel() {
        return new ApprovalModel();
    }

    /**
     * Create an instance of {@link RolesShortModel }
     * 
     */
    public RolesShortModel createRoleShortModel() {
        return new RolesShortModel();
    }

    /**
     * Create an instance of {@link LinkShortModel }
     * 
     */
    public LinkShortModel createLinkShortModel() {
        return new LinkShortModel();
    }

    /**
     * Create an instance of {@link RolesResults }
     * 
     */
    public RolesResults createRoleResults() {
        return new RolesResults();
    }


    /**
     * Create an instance of {@link ApprovalShortModel }
     * 
     */
    public ApprovalShortModel createApprovalShortModel() {
        return new ApprovalShortModel();
    }

   

}
